/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAuditRouteImport } from './routes/app/audit'
import { Route as AppCodesRouteImport } from './routes/app/codes'
import { Route as AppEfficiencyRouteImport } from './routes/app/efficiency'
import { Route as AppExceptionsRouteImport } from './routes/app/exceptions'
import { Route as AppFieldRouteImport } from './routes/app/field'
import { Route as AppJobsRouteImport } from './routes/app/jobs'
import { Route as AppPartsRouteImport } from './routes/app/parts'
import { Route as AppPayrollRouteImport } from './routes/app/payroll'
import { Route as AppPeopleRouteImport } from './routes/app/people'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppSchedulesRouteImport } from './routes/app/schedules'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppTimecardsRouteImport } from './routes/app/timecards'
import { Route as AppTruckRouteImport } from './routes/app/truck'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiIntegrationTicketsRouteImport } from './routes/api/integration/tickets'
import { Route as AppJobsTicketIdRouteImport } from './routes/app/jobs.$ticketId'
import { Route as ApiIntegrationTicketsTicketNumberRouteImport } from './routes/api/integration/tickets.$ticketNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCodesRoute = AppCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEfficiencyRoute = AppEfficiencyRouteImport.update({
  id: '/efficiency',
  path: '/efficiency',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExceptionsRoute = AppExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFieldRoute = AppFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPartsRoute = AppPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchedulesRoute = AppSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTimecardsRoute = AppTimecardsRouteImport.update({
  id: '/timecards',
  path: '/timecards',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTruckRoute = AppTruckRouteImport.update({
  id: '/truck',
  path: '/truck',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationTicketsRoute = ApiIntegrationTicketsRouteImport.update({
  id: '/api/integration/tickets',
  path: '/api/integration/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJobsTicketIdRoute = AppJobsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AppJobsRoute,
} as any)
const ApiIntegrationTicketsTicketNumberRoute =
  ApiIntegrationTicketsTicketNumberRouteImport.update({
    id: '/$ticketNumber',
    path: '/$ticketNumber',
    getParentRoute: () => ApiIntegrationTicketsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/audit': typeof AppAuditRoute
  '/app/codes': typeof AppCodesRoute
  '/app/efficiency': typeof AppEfficiencyRoute
  '/app/exceptions': typeof AppExceptionsRoute
  '/app/field': typeof AppFieldRoute
  '/app/jobs': typeof AppJobsRouteWithChildren
  '/app/parts': typeof AppPartsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/people': typeof AppPeopleRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedules': typeof AppSchedulesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/timecards': typeof AppTimecardsRoute
  '/app/truck': typeof AppTruckRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/integration/tickets': typeof ApiIntegrationTicketsRouteWithChildren
  '/app/jobs/$ticketId': typeof AppJobsTicketIdRoute
  '/api/integration/tickets/$ticketNumber': typeof ApiIntegrationTicketsTicketNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/audit': typeof AppAuditRoute
  '/app/codes': typeof AppCodesRoute
  '/app/efficiency': typeof AppEfficiencyRoute
  '/app/exceptions': typeof AppExceptionsRoute
  '/app/field': typeof AppFieldRoute
  '/app/jobs': typeof AppJobsRouteWithChildren
  '/app/parts': typeof AppPartsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/people': typeof AppPeopleRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedules': typeof AppSchedulesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/timecards': typeof AppTimecardsRoute
  '/app/truck': typeof AppTruckRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/integration/tickets': typeof ApiIntegrationTicketsRouteWithChildren
  '/app/jobs/$ticketId': typeof AppJobsTicketIdRoute
  '/api/integration/tickets/$ticketNumber': typeof ApiIntegrationTicketsTicketNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/audit': typeof AppAuditRoute
  '/app/codes': typeof AppCodesRoute
  '/app/efficiency': typeof AppEfficiencyRoute
  '/app/exceptions': typeof AppExceptionsRoute
  '/app/field': typeof AppFieldRoute
  '/app/jobs': typeof AppJobsRouteWithChildren
  '/app/parts': typeof AppPartsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/people': typeof AppPeopleRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedules': typeof AppSchedulesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/timecards': typeof AppTimecardsRoute
  '/app/truck': typeof AppTruckRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/integration/tickets': typeof ApiIntegrationTicketsRouteWithChildren
  '/app/jobs/$ticketId': typeof AppJobsTicketIdRoute
  '/api/integration/tickets/$ticketNumber': typeof ApiIntegrationTicketsTicketNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/audit'
    | '/app/codes'
    | '/app/efficiency'
    | '/app/exceptions'
    | '/app/field'
    | '/app/jobs'
    | '/app/parts'
    | '/app/payroll'
    | '/app/people'
    | '/app/reports'
    | '/app/schedules'
    | '/app/settings'
    | '/app/timecards'
    | '/app/truck'
    | '/app/'
    | '/api/auth/$'
    | '/api/integration/tickets'
    | '/app/jobs/$ticketId'
    | '/api/integration/tickets/$ticketNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/audit'
    | '/app/codes'
    | '/app/efficiency'
    | '/app/exceptions'
    | '/app/field'
    | '/app/jobs'
    | '/app/parts'
    | '/app/payroll'
    | '/app/people'
    | '/app/reports'
    | '/app/schedules'
    | '/app/settings'
    | '/app/timecards'
    | '/app/truck'
    | '/app'
    | '/api/auth/$'
    | '/api/integration/tickets'
    | '/app/jobs/$ticketId'
    | '/api/integration/tickets/$ticketNumber'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/audit'
    | '/app/codes'
    | '/app/efficiency'
    | '/app/exceptions'
    | '/app/field'
    | '/app/jobs'
    | '/app/parts'
    | '/app/payroll'
    | '/app/people'
    | '/app/reports'
    | '/app/schedules'
    | '/app/settings'
    | '/app/timecards'
    | '/app/truck'
    | '/app/'
    | '/api/auth/$'
    | '/api/integration/tickets'
    | '/app/jobs/$ticketId'
    | '/api/integration/tickets/$ticketNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiIntegrationTicketsRoute: typeof ApiIntegrationTicketsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/codes': {
      id: '/app/codes'
      path: '/codes'
      fullPath: '/app/codes'
      preLoaderRoute: typeof AppCodesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/efficiency': {
      id: '/app/efficiency'
      path: '/efficiency'
      fullPath: '/app/efficiency'
      preLoaderRoute: typeof AppEfficiencyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/exceptions': {
      id: '/app/exceptions'
      path: '/exceptions'
      fullPath: '/app/exceptions'
      preLoaderRoute: typeof AppExceptionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/field': {
      id: '/app/field'
      path: '/field'
      fullPath: '/app/field'
      preLoaderRoute: typeof AppFieldRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/parts': {
      id: '/app/parts'
      path: '/parts'
      fullPath: '/app/parts'
      preLoaderRoute: typeof AppPartsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/payroll': {
      id: '/app/payroll'
      path: '/payroll'
      fullPath: '/app/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/schedules': {
      id: '/app/schedules'
      path: '/schedules'
      fullPath: '/app/schedules'
      preLoaderRoute: typeof AppSchedulesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/timecards': {
      id: '/app/timecards'
      path: '/timecards'
      fullPath: '/app/timecards'
      preLoaderRoute: typeof AppTimecardsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/truck': {
      id: '/app/truck'
      path: '/truck'
      fullPath: '/app/truck'
      preLoaderRoute: typeof AppTruckRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integration/tickets': {
      id: '/api/integration/tickets'
      path: '/api/integration/tickets'
      fullPath: '/api/integration/tickets'
      preLoaderRoute: typeof ApiIntegrationTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/jobs/$ticketId': {
      id: '/app/jobs/$ticketId'
      path: '/$ticketId'
      fullPath: '/app/jobs/$ticketId'
      preLoaderRoute: typeof AppJobsTicketIdRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/api/integration/tickets/$ticketNumber': {
      id: '/api/integration/tickets/$ticketNumber'
      path: '/$ticketNumber'
      fullPath: '/api/integration/tickets/$ticketNumber'
      preLoaderRoute: typeof ApiIntegrationTicketsTicketNumberRouteImport
      parentRoute: typeof ApiIntegrationTicketsRoute
    }
  }
}

interface AppJobsRouteChildren {
  AppJobsTicketIdRoute: typeof AppJobsTicketIdRoute
}

const AppJobsRouteChildren: AppJobsRouteChildren = {
  AppJobsTicketIdRoute: AppJobsTicketIdRoute,
}

const AppJobsRouteWithChildren =
  AppJobsRoute._addFileChildren(AppJobsRouteChildren)

interface AppRouteRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppCodesRoute: typeof AppCodesRoute
  AppEfficiencyRoute: typeof AppEfficiencyRoute
  AppExceptionsRoute: typeof AppExceptionsRoute
  AppFieldRoute: typeof AppFieldRoute
  AppJobsRoute: typeof AppJobsRouteWithChildren
  AppPartsRoute: typeof AppPartsRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSchedulesRoute: typeof AppSchedulesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTimecardsRoute: typeof AppTimecardsRoute
  AppTruckRoute: typeof AppTruckRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppCodesRoute: AppCodesRoute,
  AppEfficiencyRoute: AppEfficiencyRoute,
  AppExceptionsRoute: AppExceptionsRoute,
  AppFieldRoute: AppFieldRoute,
  AppJobsRoute: AppJobsRouteWithChildren,
  AppPartsRoute: AppPartsRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppReportsRoute: AppReportsRoute,
  AppSchedulesRoute: AppSchedulesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTimecardsRoute: AppTimecardsRoute,
  AppTruckRoute: AppTruckRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ApiIntegrationTicketsRouteChildren {
  ApiIntegrationTicketsTicketNumberRoute: typeof ApiIntegrationTicketsTicketNumberRoute
}

const ApiIntegrationTicketsRouteChildren: ApiIntegrationTicketsRouteChildren = {
  ApiIntegrationTicketsTicketNumberRoute:
    ApiIntegrationTicketsTicketNumberRoute,
}

const ApiIntegrationTicketsRouteWithChildren =
  ApiIntegrationTicketsRoute._addFileChildren(
    ApiIntegrationTicketsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiIntegrationTicketsRoute: ApiIntegrationTicketsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
